name: Execução Diária do Robô
on:
  schedule:
    - cron: '0 10 * * *'  # Executa diariamente às 10:00
  workflow_dispatch:

jobs:
  executar:
    runs-on: ubuntu-latest
    steps:
      - name: clonar repositório
        uses: actions/checkout@v3

      - name: Commit do relatorio
        run: |
          git config --global user "github-action"
          git config --global user.email "270210.gui@gmail.com"
          git add dados/relatorio.csv
          git commit -m "Atualização diaria"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
